#!/bin/bash

# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
setup_bosh_access

last_ref=$(jq -r '.version.ref // ""' < $payload)
new_ref="$(calc_reference)"

if [[ "$new_ref" == "$last_ref" ]]
then
  echo "[]" >&3
else
  jq -n "[
    {\"ref\": \"$new_ref\"}
  ]" >&3
fi
