#!/bin/sh

# echo '{"version": {"ref": "123"}}'

# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

source $(dirname $0)/common.sh

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

cat <<SCRIPT > $destination/$filename
#!$shell
$body
SCRIPT

chmod 755 $destination/$filename

new_ref="$(calc_reference)"

jq -n "{
  \"version\": {\"ref\": \"$new_ref\"},
  \"metadata\": [{\"name\": \"filename\", \"value\": \"$filename\"}]
}" >&3
